FROM python:3.9-slim-buster

WORKDIR /src

# Install build dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libffi-dev \
    libssl-dev \
    wget \
    curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install Poetry
RUN pip install poetry

# Copy project files
COPY ./pyproject.toml .
# COPY ./poetry.lock .

# Install Python dependencies
RUN poetry config virtualenvs.create false \
    && poetry install

# Copy application files
COPY ./config.py .
COPY ./run.py .
COPY ./app/ ./app
COPY ./data/ ./data

EXPOSE 5000

CMD ["python3", "run.py"]
